import { removeManagedSkill, syncManagedSkill } from './managed-skills'

export const AGENT_SKILL_NAME = 'lodestar-agent'

export function agentSkillBody(): string {
  const description = 'Call a configured identity as its corresponding Agent through Lodestar for implementation, debugging, research, planning, review, testing, or parallel work. Use whenever the user asks to call another model, AI, or Agent, or when the main Agent deliberately delegates a task.'
  return [
    '---',
    `name: ${AGENT_SKILL_NAME}`,
    `description: ${JSON.stringify(description)}`,
    '---',
    '',
    '# lodestar-agent',
    '',
    'Use Lodestar to call the Agent represented by a selected live identity.',
    'Each identity resolves to its configured Token Source, provider Agent backend,',
    'model, and effort. The caller-supplied prompt becomes that Agent run\'s task.',
    '',
    '## Required workflow',
    '',
    '1. Query the live identity catalog immediately before every new task:',
    '',
    '```bash',
    '# desc: 查询当前可用的 Agent 身份',
    'lodestar-agent identities --json',
    '```',
    '',
    '2. Select only identities with `status: "ready"`. Never invent, cache,',
    '   substitute, or silently downgrade an identity/model/effort.',
    '3. Give the child the complete task, relevant context, authority boundaries,',
    '   expected deliverable, and verification requirements in the raw prompt.',
    '4. For the same prompt sent to several models, pass every identity to one run',
    '   with repeated `--identity`; the daemon fans them out concurrently.',
    '5. Wait for the result. Attribute each result to its actual model and surface',
    '   failures. Child file changes are live in the same workspace.',
    '',
    '## Run a task',
    '',
    '```bash',
    '# desc: 把完整任务交给指定 Agent',
    "lodestar-agent run --identity '<identity-id>' --stdin <<'EOF'",
    '<raw task prompt written by the main Agent>',
    'EOF',
    '```',
    '',
    '## Continue the same native Agent session',
    '',
    '```bash',
    '# desc: 在同一原生 Agent 会话中继续任务',
    "lodestar-agent follow-up '<run-id>' --identity '<identity-id>' --stdin <<'EOF'",
    '<follow-up prompt>',
    'EOF',
    '```',
    '',
    '## Answer a child question',
    '',
    'When a run returns `Status: needs_input`, answer the exact request id. JSON',
    'keys may be the question id or the full question text:',
    '',
    '```bash',
    '# desc: 回答 Agent 的阻塞问题并继续运行',
    "lodestar-agent answer '<run-id>' --identity '<identity-id>' --request '<request-id>' --stdin <<'EOF'",
    '{"question-id":"answer"}',
    'EOF',
    '```',
    '',
    '## Boundaries',
    '',
    '- Do not invoke provider CLIs or provider HTTP APIs directly for delegation.',
    '- Never expose `LODESTAR_AGENT_CAPABILITY` in prompts, output, logs, or args.',
    '- A non-zero command exit is a real failure. Do not claim the child succeeded.',
    '- Scope the Agent task and authorized actions to the user request.',
    '',
  ].join('\n')
}

export function ensureLodestarAgentSkill(): void {
  removeManagedSkill('lodestar-consult')
  syncManagedSkill({ name: AGENT_SKILL_NAME, body: agentSkillBody() })
}
