import { syncManagedSkill } from './managed-skills'

export const CONSULT_SKILL_NAME = 'lodestar-consult'

export function consultSkillBody(): string {
  const description = 'Run any code, change, plan, architecture, security, testing, or correctness review, and consult, ask, or obtain a second opinion from another configured model, LLM, AI, or agent through Lodestar. Always use this skill for every review request and whenever the user asks to "让 DeepSeek 审查", "问一下 GLM5.3", "找其他模型看看", "多模型评审", "交叉复核", "ask another AI/model/agent", or "second opinion". Discover identities first; batch every selected identity into exactly one Lodestar run so reviewers execute concurrently; never call provider CLIs directly.'
  return [
    '---',
    `name: ${CONSULT_SKILL_NAME}`,
    `description: ${JSON.stringify(description)}`,
    '---',
    '',
    '# lodestar-consult',
    '',
    "Use Lodestar's configured reviewer identities to ask another model or run an",
    'independent review. The daemon owns credentials, model routing, read-only',
    'isolation, unrestricted network access, progress cards, cancellation, and result capture.',
    '',
    '## Required workflow',
    '',
    '1. Always query the live identity catalog first:',
    '',
    '```bash',
    '# desc: 查询当前可用的全局评审身份',
    'lodestar-consult identities --json',
    '```',
    '',
    '2. Select only identities returned by that command with `status: "ready"`.',
    '   Never reuse an id from an earlier turn and never invent or substitute a model.',
    '3. Finish selecting the complete identity set before starting any run. If two',
    '   or more identities are selected, pass every id to exactly one command using',
    '   repeated `--identity` flags. This single-run batch is mandatory for concurrency.',
    "4. Resolve the user's wording:",
    '   - Exact model request (for example `GLM-5.3`): exact normalized model match.',
    '   - Token Source/family only (for example `DeepSeek`): select that source\'s',
    '     unique `source_default: true` identity.',
    '   - Named global role: prefer the matching `origin: "preset"` identity.',
    '   - Generic review without a named model: prefer a ready preset matching',
    '     the requested review role; otherwise choose one relevant ready',
    '     source-default catalog identity and state which identity was used.',
    "   - Ambiguous matches: ask the user with the host's native question tool.",
    '   - "several/other models": choose a small relevant set from different token',
    '     sources. Call every ready identity only when the user explicitly asks for all.',
    '5. Run the consultation and wait for its terminal report. Attribute every result',
    '   to the actual identity/model and surface failures without replacing them.',
    '6. If no suitable ready identity exists, show the catalog failure and tell the',
    '   user to configure accounts with `model` or global roles with `reviewers`.',
    '',
    '## Mandatory batching',
    '',
    '- Never launch one `lodestar-consult run` per identity, whether sequentially,',
    '  as background tasks, with shell parallelism, or in separate tool calls.',
    '- The daemon permits one active run per project group. Reviewer concurrency is',
    '  server-side fan-out inside one run; separate run commands serialize or conflict.',
    '- Query once, select all identities, issue one run, and wait once.',
    '',
    '## Ask another model',
    '',
    '```bash',
    '# desc: 请求指定模型回答独立咨询',
    "lodestar-consult run --identity '<identity-id>' --kind question --stdin <<'EOF'",
    '<question and only the context that materially helps>',
    'EOF',
    '```',
    '',
    '## Review current changes',
    '',
    '```bash',
    '# desc: 并发请求多个模型审查当前未提交变更',
    "lodestar-consult run --identity '<identity-id-1>' --identity '<identity-id-2>' --kind review --target uncommitted_changes",
    '```',
    '',
    'Keep adding `--identity` flags to this same command for all selected reviewers.',
    'Add `--cross-review` to the same run only when the user asks for cross-review,',
    'debate, consensus, or reviewers to critique each other.',
    '',
    '## Review a proposal',
    '',
    '```bash',
    '# desc: 请求指定模型复核当前方案',
    "lodestar-consult run --identity '<identity-id>' --kind review --target proposal --stdin <<'EOF'",
    '<proposal>',
    'EOF',
    '```',
    '',
    '## Boundaries',
    '',
    '- Do not run `codex`, `claude`, or provider HTTP APIs directly for this task.',
    '- Do not expose `LODESTAR_CONSULT_CAPABILITY` in output, logs, or command args.',
    '- A non-zero command exit is a real consultation failure. Report it; do not',
    '  continue as though consensus succeeded.',
    '- Reviewer output is advisory. Check its evidence before applying changes.',
    '',
  ].join('\n')
}

export function ensureLodestarConsultSkill(): void {
  syncManagedSkill({ name: CONSULT_SKILL_NAME, body: consultSkillBody() })
}
